# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  venvbuild:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements-dev.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements-dev.txt" }}

      # run tests using requirements.txt
      - run:
          name: run tests
          command: |
            mkdir -p ~/pytest_results
            python3 -m venv venv
            . venv/bin/activate
            pytest tests --ignore tests/archived

      - store_artifacts:
          path: test-reports

      - store_test_results:
          path: ~/pytest_results

  setupbuild:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout


      - run:
          name: install dependencies
          command: |
            pip3 install .
            pip3 install pytest

      # run tests using requirements.txt
      - run:
          name: run tests
          command: |
            pytest tests --ignore tests/archived

      - store_artifacts:
          path: test-reports

      - store_test_results:
          path: ~/pytest_results

workflows:
  version: 2
  build_and_test:
    jobs:
      - venvbuild
      - setupbuild