# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.2

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}

      - run:
          name: install dependencies
          command: |
            curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
            source $HOME/.poetry/env
            poetry install

      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs


      # run tests using requirements.txt
      - run:
          name: run tests
          command: |
            mkdir -p ~/pytest_results
            poetry run pytest tests --ignore tests/tests_with_server_and_cached_results

      - store_artifacts:
          path: test-reports

      - store_test_results:
          path: ~/pytest_results

#  deploy:
#    docker:
#      - image: circleci/python:3.6
#    steps:
#      - checkout
#
#      - restore_cache:
#          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
#
#      - run:
#          name: install python dependencies
#          command: |
#            python3 -m venv venv
#            . venv/bin/activate
#            pip install -r requirements-dev.txt
#
#      - save_cache:
#          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
#          paths:
#            - "venv"
#
#      - run:
#          name: verify git tag vs. version
#          command: |
#            python3 -m venv venv
#            . venv/bin/activate
#            python setup.py verify
#
#      - run:
#          name: init .pypirc
#          command: |
#            echo -e "[pypi]" >> ~/.pypirc
#            echo -e "username = $PYPI_USER" >> ~/.pypirc
#            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
#
#      - run:
#          name: create packages
#          command: |
#            make deploy
#
#      - run:
#          name: upload to pypi
#          command: |
#            . venv/bin/activate
#            twine upload dist/*


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/